### ISSUE TITLE
Generated Resolvers are non-optimal

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-rad-datomic#23]
The generated resolvers in this plugin generate a pull request for everything an entity *could* have instead of what the resolver has been asked for. This generates unnecessary IO on the database.

**Comment by holyjak** [comment]
Isn't this addressed by https://github.com/fulcrologic/fulcro-rad-datomic/commit/658cb3548f6a2024202aa0799651563940b189f9 ? The commit message reads "Minimal pulls: Turning this on reduces pull queries to just what the client asked for"

**Comment by awkay** [comment]
yes, thanks
