### ISSUE TITLE
Broken compatibility with Pathom 3

### ISSUE THREAD

**Issue by holyjak** [fulcrologic/fulcro-rad-datomic#26]
The recent change https://github.com/fulcrologic/fulcro-rad-datomic/commit/658cb3548f6a2024202aa0799651563940b189f9#diff-fc8f7b85570d9a211b3e4904ab2555761bddf5eae5fb48070bea4c53db4c377dR14 introduces `com.wsscode.pathom.core` to `com.fulcrologic.rad.database-adapters.datomic-common` and the plugin will thus fail to load in a RAD project that only uses Pathom 2.

A possibly workaround is to have both v2 and 3 on the classpath, but then it is likely the new code won't work as intended under Pathom 3.

~In Pathom 3, there is `:com.wsscode.pathom3.connect.runner/root-query [{:product/all-products [...]}]`, which I guess is equivallent of P2's  `client-query` . (P3 also has `:com.wsscode.pathom3.interface.eql/source-request :pathom/ast` with `{:type :root, :children [..]}` with the AST of that query, but to support both P2 and P3, it is likely best to use the raw 3 query)~ _I realize now that root-query is something very different from parent-query (which is specific to the current resolver). I've [asked for advice in #pathom](https://clojurians.slack.com/archives/C87NB2CFN/p1697290211898459)._

The simple fix is to replace `:as` with `:as-alias` in the require, and do not support minimal-pull? for Pathom 3. I am trying to figure out whether we can do something better for P3... .

**Comment by awkay** [comment]
It's only used for a keyword...I've removed the rquire.
